### ISSUE TITLE
Support Django 3.1.*

### ISSUE THREAD

**Issue by AlexObukhoff** [escaped/django-inline-actions#35]
Please support django 3.1 
Now I take exception 
```
2020-12-11 22:38:31,366 django.request ERROR Internal Server Error: /admin/term_admin/terminal/999/change/
Traceback (most recent call last):
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\core\handlers\base.py", line 179, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 614, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\views\decorators\cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\sites.py", line 233, in inner
    return view(request, *args, **kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 1656, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "C:\Projects\CloudFR.new\django-app\cloudfr\apps\inline_actions\admin.py", line 283, in changeform_view
    request, object_id, form_url, extra_context)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\utils\decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 1534, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 1598, in _changeform_view
    formsets, inline_instances = self._create_formsets(request, obj, change=True)
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 1954, in _create_formsets
    for FormSet, inline in self.get_formsets_with_inlines(*get_formsets_args):
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 797, in get_formsets_with_inlines
    for inline in self.get_inline_instances(request, obj):
  File "C:\Users\alex\.virtualenvs\django-app-8FcSrxQE\lib\site-packages\django\contrib\admin\options.py", line 603, in get_inline_instances
    if not inline.has_add_permission(request, obj):
TypeError: has_add_permission() takes 2 positional arguments but 3 were given
```

**Comment by escaped** [comment]
Thanks for the bug report. Will look into it, but PRs are welcome as well :)

**Comment by escaped** [comment]
Thanks again for reporting the issue. I just looked into the issue and could not identify any problems with this library itself; only in the example project, which is not affecting other projects. Still, I had to [update](https://github.com/escaped/django-inline-actions/pull/37) the documentation, as the `Example 1` is not valid anymore.

Anyway, I suspect, that you have to update the `has_add_permission()` signature in your project as since [Django `3.0` a third optional argument is required](https://code.djangoproject.com/ticket/27991).

Django `2.x`:
```python
    ...
    def has_add_permission(self, request):
        ...
    ...
```

Django `3.x`:
```python
    ...
    def has_add_permission(self, request, obj=None):
        ...
    ...
```

**Comment by escaped** [comment]
Looks like nothing else needs to be done. Closing for now :)
